### PR TITLE
Adds project makefile (specially for install job)

### PR DESCRIPTION
**Pull request by aeten**
Hello,
I add a makefile with an install and Debian package building tasks. I Hope you find this usefull.
Best regards,
Thomas Pérennou

### CODE REVIEW

**Comment by StreakyCobra** [comment]
Hi,

Thanks for the contribution. I'm just coming back from holidays, I'll for sure look at it the next few days/weeks!

**Comment by StreakyCobra** [comment]
I already merged the commit concerning git aliases (8298fc664f572a8d2761423daa989b17d518e92f). Nice catch!

The `makefile` is mostly Debian specific right? If yes, is it possible to move it to the `debian` folder – or at least to rename it to `debian-makefile` – without breaking its purpose? (I don't know anything about Debian build system :confused: ) I want to avoid people trying to call make on non-Debian systems, or thinking there is something to build for using it.

Btw: The `tests` folder and its `Makefile` is a little bit misleading here. No tests are made, this is just building a workspace with different states, to test gws manually later. There is no interest of running it as default target.

**Comment by aeten** [comment]
Here is it.
I have kept the makefile in place but deactivated the debian task when required tools are not available.
Tell me if you really move the debian part into its own makefile, I will do it.

**Comment by StreakyCobra** [comment]
Seems better to me, thanks. Let starts with this Makefile and I'll update or move it later if needed.

**Comment by emlun** [comment]
This is now merged into master, but I moved the Debian files into the `packaging/debian` directory and updated the file paths as best as I could (see dc91278). Does that still work? Feel free to reopen this if there's anything that needs fixing.

**Pull request closed without merging**
